from shared.schemas import (
    InvestigationReport, AgentResponse, EvidenceItem,
    EvidenceChainStep, RiskLevel
)
from jinja2 import Template
import uuid


REPORT_TEMPLATE = """# Shadow Intel Investigation Report

**Entity:** {{ report.entity_name }}
**Report ID:** {{ report.report_id }}
**Generated:** {{ report.generated_at.strftime('%Y-%m-%d %H:%M UTC') }}
**Risk Level:** {{ report.risk_level.value.upper() }}
**Confidence:** {{ (report.unified_confidence * 100)|round(1) }}%

---

## Summary

{{ report.narrative_summary }}

---

## Evidence Chain

{% for step in report.evidence_chain %}
**Step {{ step.step }}** — {{ step.source_module }}
{{ step.finding }}
Sources: {{ step.sources | join(', ') }}
Confidence: {{ (step.confidence * 100)|round(1) }}%

{% endfor %}

---

## Evidence Items ({{ report.evidence_chain | length }} total)

{% for step in report.evidence_chain %}
- [{{ step.source_module }}] {{ step.finding }}
{% endfor %}

---

*Generated by Shadow Intel | Agents League Hackathon 2026*
"""


def build_evidence_chain(
    ghost: AgentResponse | None,
    money: AgentResponse | None,
    ownership: AgentResponse | None,
    signal: AgentResponse | None,
) -> list[EvidenceChainStep]:
    chain = []
    step = 1

    agents = [
        ("ghost_tracker", ghost),
        ("money_trail", money),
        ("ownership_unwind", ownership),
        ("dark_signal", signal),
    ]

    for module_name, agent in agents:
        if agent and agent.evidence:
            top = sorted(agent.evidence, key=lambda e: e.confidence, reverse=True)[:3]
            chain.append(EvidenceChainStep(
                step=step,
                finding=top[0].detail if top else f"No findings from {module_name}",
                source_module=module_name,
                sources=[e.source for e in top],
                confidence=agent.risk_score,
            ))
            step += 1

    return chain


def build_report(
    entity_id: str,
    entity_name: str,
    ghost: AgentResponse | None,
    money: AgentResponse | None,
    ownership: AgentResponse | None,
    signal: AgentResponse | None,
    resurface: AgentResponse | None,
    unified_confidence: float,
    risk_level: RiskLevel,
    narrative: str,
) -> InvestigationReport:
    evidence_chain = build_evidence_chain(ghost, money, ownership, signal)

    report = InvestigationReport(
        entity_id=entity_id,
        entity_name=entity_name,
        unified_confidence=unified_confidence,
        risk_level=risk_level,
        narrative_summary=narrative,
        evidence_chain=evidence_chain,
        ghost_tracker=ghost,
        money_trail=money,
        ownership_unwind=ownership,
        dark_signal=signal,
        resurface_watch=resurface,
    )

    template = Template(REPORT_TEMPLATE)
    report.report_markdown = template.render(report=report)

    return report
