"""
Investigation report builder.
Assembles the final InvestigationReport from all agent outputs,
the merged evidence set, the unified confidence score, and the
Foundry IQ narrative. Also renders the human-readable Markdown report.
"""

from jinja2 import Template

from shared.schemas import (
    InvestigationReport, AgentResponse, EvidenceItem,
    EvidenceChainStep, RiskLevel, EntityFingerprint,
)
from shared.logger import get_logger

logger = get_logger(__name__)


# ─── Markdown report template ─────────────────────────────────────────────────

MARKDOWN_TEMPLATE = """\
# Shadow Intel — Investigation Report

| Field | Value |
|---|---|
| **Entity** | {{ report.entity_name }} |
| **Report ID** | `{{ report.report_id }}` |
| **Generated** | {{ report.generated_at.strftime('%Y-%m-%d %H:%M UTC') }} |
| **Risk Level** | **{{ report.risk_level.value.upper() }}** |
| **Confidence** | {{ (report.unified_confidence * 100) | round(1) }}% |

---

## Foundry IQ — Investigation Summary

> *Powered by Azure AI Foundry*

{{ report.narrative_summary }}

---

## Evidence Chain

{% for step in report.evidence_chain %}
### Step {{ step.step }} — {{ step.source_module | replace('_', ' ') | title }}

**Confidence:** {{ (step.confidence * 100) | round(1) }}%
**Sources:** {{ step.sources | join(', ') }}

{{ step.finding }}

{% endfor %}

---

## Agent Results

| Agent | Status | Risk Score | Evidence Items | Time (ms) |
|---|---|---|---|---|
{% for agent_name, agent in agents.items() %}\
| {{ agent_name | replace('_', ' ') | title }} \
| {{ agent.status.value if agent else 'not run' }} \
| {{ '%.1f' % (agent.risk_score * 100) if agent else '-' }}% \
| {{ agent.evidence | length if agent else '-' }} \
| {{ agent.processing_time_ms if agent else '-' }} |
{% endfor %}

---

## Key Evidence (Top 10)

{% for item in top_evidence %}\
- **[{{ item.source }}]** {{ item.detail }}{% if item.url %} — [source]({{ item.url }}){% endif %}

{% endfor %}

---

## Entity Fingerprint

- **Canonical Name:** {{ fingerprint.canonical_name }}
- **Known Aliases:** {{ fingerprint.aliases | join(', ') if fingerprint.aliases else 'None detected' }}
- **Jurisdictions:** {{ fingerprint.jurisdictions | join(', ') if fingerprint.jurisdictions else 'None detected' }}
- **Sanctions Lists:** {{ fingerprint.sanctions_lists | join(', ') if fingerprint.sanctions_lists else 'None' }}
- **Registration Numbers:** {{ fingerprint.registration_numbers | join(', ') if fingerprint.registration_numbers else 'None' }}

---

*Generated by Shadow Intel | Agents League Hackathon 2026*
*Corporate data: OpenCorporates (opencorporates.com) — open licence*
*Sanctions data: OFAC · UN Security Council · OpenSanctions*
"""


# ─── Evidence chain builder ───────────────────────────────────────────────────

def _build_evidence_chain(
    ghost:     AgentResponse | None,
    money:     AgentResponse | None,
    ownership: AgentResponse | None,
    signal:    AgentResponse | None,
    resurface: AgentResponse | None,
) -> list[EvidenceChainStep]:
    """
    Build an ordered evidence chain from all agent results.
    Each chain step summarises the top finding from one agent.
    Steps are only added for agents that ran successfully.
    """
    chain: list[EvidenceChainStep] = []
    step_num = 1

    agent_steps: list[tuple[str, AgentResponse | None]] = [
        ("ghost_tracker",    ghost),
        ("money_trail",      money),
        ("ownership_unwind", ownership),
        ("dark_signal",      signal),
        ("resurface_engine", resurface),
    ]

    for module_name, agent in agent_steps:
        if not agent or agent.status.value == "failed":
            continue

        if agent.evidence:
            top = sorted(agent.evidence, key=lambda e: e.confidence, reverse=True)
            finding = top[0].detail
            sources = list(dict.fromkeys(e.source for e in top[:3]))  # ordered dedup
        else:
            finding = f"No significant findings from {module_name.replace('_', ' ')}."
            sources = [module_name]

        chain.append(EvidenceChainStep(
            step=step_num,
            finding=finding,
            source_module=module_name,
            sources=sources,
            confidence=agent.risk_score,
        ))
        step_num += 1

    return chain


# ─── Public API ───────────────────────────────────────────────────────────────

def build_report(
    entity_id:          str,
    entity_name:        str,
    fingerprint:        EntityFingerprint,
    ghost:              AgentResponse | None,
    money:              AgentResponse | None,
    ownership:          AgentResponse | None,
    signal:             AgentResponse | None,
    resurface:          AgentResponse | None,
    merged_evidence:    list[EvidenceItem],
    unified_confidence: float,
    risk_level:         RiskLevel,
    narrative:          str,
) -> InvestigationReport:
    """
    Assemble the full InvestigationReport from all components and
    render its Markdown representation.

    Returns the complete report ready for session storage and API response.
    """
    evidence_chain = _build_evidence_chain(ghost, money, ownership, signal, resurface)

    report = InvestigationReport(
        entity_id=entity_id,
        entity_name=entity_name,
        unified_confidence=unified_confidence,
        risk_level=risk_level,
        narrative_summary=narrative,
        evidence_chain=evidence_chain,
        ghost_tracker=ghost,
        money_trail=money,
        ownership_unwind=ownership,
        dark_signal=signal,
        resurface_watch=resurface,
    )

    # ── Render Markdown ────────────────────────────────────────────────────
    agents_dict: dict[str, AgentResponse | None] = {
        "ghost_tracker":    ghost,
        "money_trail":      money,
        "ownership_unwind": ownership,
        "dark_signal":      signal,
        "resurface_engine": resurface,
    }
    top_evidence = sorted(merged_evidence, key=lambda e: e.confidence, reverse=True)[:10]

    try:
        template = Template(MARKDOWN_TEMPLATE)
        report.report_markdown = template.render(
            report=report,
            agents=agents_dict,
            top_evidence=top_evidence,
            fingerprint=fingerprint,
        )
    except Exception as exc:
        logger.error(f"Failed to render Markdown report: {exc}")
        # Minimal fallback so the report is never missing its markdown field
        report.report_markdown = f"# Investigation Report\n\n{narrative}"

    logger.info(
        f"Report built | "
        f"entity='{entity_name}' | "
        f"confidence={unified_confidence:.1%} | "
        f"risk={risk_level.value} | "
        f"chain_steps={len(evidence_chain)} | "
        f"evidence_total={len(merged_evidence)}"
    )

    return report
