from msgraph import GraphServiceClient
from msgraph.generated.models.message import Message
from msgraph.generated.models.item_body import ItemBody
from msgraph.generated.models.recipient import Recipient
from msgraph.generated.models.email_address import EmailAddress
from azure.identity import ClientSecretCredential
from shared.config import get_settings
from shared.schemas import AlertPayload
from shared.logger import get_logger

logger = get_logger(__name__)


def _get_graph_client() -> GraphServiceClient:
    settings = get_settings()
    credential = ClientSecretCredential(
        tenant_id=settings.graph_tenant_id,
        client_id=settings.graph_client_id,
        client_secret=settings.graph_client_secret,
    )
    return GraphServiceClient(credentials=credential)


async def send_outlook_alert(alert: AlertPayload, recipient_email: str) -> bool:
    """
    Send a Shadow Intel alert email via Microsoft Outlook (Graph API).
    Uses the 'me/sendMail' endpoint — requires Mail.Send permission.
    """
    risk_label = alert.risk_level.value.upper()
    subject = f"[Shadow Intel] {risk_label} Alert: {alert.entity_name}"

    body_html = f"""
<html><body>
<h2 style="color: #c0392b;">Shadow Intel Intelligence Alert</h2>
<table style="border-collapse: collapse; width: 100%;">
  <tr><td><b>Entity</b></td><td>{alert.entity_name}</td></tr>
  <tr><td><b>Risk Level</b></td><td>{risk_label}</td></tr>
  <tr><td><b>Confidence</b></td><td>{alert.confidence * 100:.1f}%</td></tr>
  <tr><td><b>Event</b></td><td>{alert.match_event}</td></tr>
  <tr><td><b>Jurisdiction</b></td><td>{alert.jurisdiction or 'Unknown'}</td></tr>
</table>
<h3>Top Evidence</h3>
<ul>{''.join(f'<li>{e}</li>' for e in alert.top_evidence[:5])}</ul>
<p><a href="{alert.report_url}">View Full Shadow Intel Report</a></p>
<hr><small>Generated by Shadow Intel | Agents League Hackathon 2026</small>
</body></html>
"""

    try:
        client = _get_graph_client()
        send_mail_body = {
            "message": {
                "subject": subject,
                "body": {"contentType": "HTML", "content": body_html},
                "toRecipients": [{"emailAddress": {"address": recipient_email}}],
            }
        }
        # TODO: call client.me.send_mail.post(body=send_mail_body)
        logger.info(f"Outlook alert queued for {recipient_email}: {alert.entity_name}")
        return True
    except Exception as e:
        logger.error(f"Outlook alert failed: {e}")
        return False
