from shared.config import get_settings
from shared.schemas import AlertPayload
from shared.logger import get_logger
from alerts.graph_client import send_graph_mail

logger = get_logger(__name__)

def build_email_alert(alert: AlertPayload) -> str:
    """Generate structured HTML email briefing for the analyst."""
    risk_label = alert.risk_level.value.upper()
    
    evidence_html = "".join([f"<li>{ev}</li>" for ev in alert.top_evidence[:5]])
    
    body_html = f"""
    <html>
    <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
        <h2 style="color: #c0392b;">🚨 Shadow Intel Intelligence Alert</h2>
        <table style="border-collapse: collapse; width: 100%; max-width: 600px;">
            <tr><td style="padding: 8px; border-bottom: 1px solid #ddd;"><b>Entity</b></td><td style="padding: 8px; border-bottom: 1px solid #ddd;">{alert.entity_name}</td></tr>
            <tr><td style="padding: 8px; border-bottom: 1px solid #ddd;"><b>Confidence Score</b></td><td style="padding: 8px; border-bottom: 1px solid #ddd;">{alert.confidence * 100:.1f}%</td></tr>
            <tr><td style="padding: 8px; border-bottom: 1px solid #ddd;"><b>Jurisdiction</b></td><td style="padding: 8px; border-bottom: 1px solid #ddd;">{alert.jurisdiction or 'Unknown'}</td></tr>
            <tr><td style="padding: 8px; border-bottom: 1px solid #ddd;"><b>Alert Reason</b></td><td style="padding: 8px; border-bottom: 1px solid #ddd;">{alert.match_event}</td></tr>
            <tr><td style="padding: 8px; border-bottom: 1px solid #ddd;"><b>Risk Level</b></td><td style="padding: 8px; border-bottom: 1px solid #ddd; font-weight: bold; color: #c0392b;">{risk_label}</td></tr>
        </table>
        
        <h3>Evidence Summary</h3>
        <ul>
            {evidence_html}
        </ul>
        
        <p style="margin-top: 20px;">
            <a href="{alert.report_url or f'https://shadowintel.com/investigate/{alert.entity_id}'}" style="background-color: #2980b9; color: white; padding: 10px 15px; text-decoration: none; border-radius: 4px;">View Full Shadow Intel Report</a>
        </p>
        
        <hr style="margin-top: 30px; border: 0; border-top: 1px solid #eee;">
        <p style="font-size: 12px; color: #7f8c8d;">
            Generated by Shadow Intel Alert Engine<br>
            Timestamp: {alert.timestamp.isoformat() if hasattr(alert, 'timestamp') and alert.timestamp else 'Current'}
        </p>
    </body>
    </html>
    """
    return body_html

async def send_outlook_alert(alert: AlertPayload, recipient_email: str) -> bool:
    """
    Send a Shadow Intel alert email via Microsoft Outlook (Graph API).
    """
    settings = get_settings()
    sender_email = settings.graph_sender_email
    
    if not sender_email:
        logger.warning("GRAPH_SENDER_EMAIL is not configured — skipping Outlook alert")
        return False
        
    risk_label = alert.risk_level.value.upper()
    
    # Priority Flag is in the subject if Critical
    is_critical = "Critical" in risk_label or "CRITICAL" in risk_label
    subject = f"{'[PRIORITY] ' if is_critical else ''}[Shadow Intel] {risk_label} Alert: {alert.entity_name}"
    
    body_html = build_email_alert(alert)
    
    logger.info(f"Queuing Outlook alert for {recipient_email}: {alert.entity_name}")
    
    return await send_graph_mail(
        sender_email=sender_email,
        recipient_email=recipient_email,
        subject=subject,
        html_body=body_html
    )
